//go:build ignore

package main

import (
	"fmt"
	"os"
	"text/template"
)

type SlotEntity struct {
	EntityType      string
	EntityTable     string
	FileTable       string
	AssignTable     string
	EntityIDCol     string
	FileAlias       string
	AssignAlias     string
	FileTitleCols   string
	AssignTitleCols string
	FileEntityJoins string
	AssignEntityJoins string
	FileTitleOrder  string
	AssignTitleOrder string
}

var entities = []SlotEntity{
	{
		EntityType:      "Movie",
		EntityTable:     "movies",
		FileTable:       "movie_files",
		AssignTable:     "movie_slot_assignments",
		EntityIDCol:     "movie_id",
		FileAlias:       "mf",
		AssignAlias:     "msa",
		FileTitleCols:   "m.title as movie_title",
		AssignTitleCols: "m.title as movie_title",
		FileEntityJoins: "JOIN movies m ON mf.movie_id = m.id",
		AssignEntityJoins: "JOIN movies m ON msa.movie_id = m.id",
		FileTitleOrder:  "m.title",
		AssignTitleOrder: "m.title",
	},
	{
		EntityType:      "Episode",
		EntityTable:     "episodes",
		FileTable:       "episode_files",
		AssignTable:     "episode_slot_assignments",
		EntityIDCol:     "episode_id",
		FileAlias:       "ef",
		AssignAlias:     "esa",
		FileTitleCols:   "e.title as episode_title, e.season_number, e.episode_number, s.title as series_title",
		AssignTitleCols: "e.title as episode_title, e.season_number, e.episode_number, s.title as series_title",
		FileEntityJoins: "JOIN episodes e ON ef.episode_id = e.id\nJOIN series s ON e.series_id = s.id",
		AssignEntityJoins: "JOIN episodes e ON esa.episode_id = e.id\nJOIN series s ON e.series_id = s.id",
		FileTitleOrder:  "s.title, e.season_number, e.episode_number",
		AssignTitleOrder: "s.title, e.season_number, e.episode_number",
	},
}

func main() {
	tmplContent, err := os.ReadFile("slots_template.sql.tmpl")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading template: %v\n", err)
		os.Exit(1)
	}
	tmpl := template.Must(template.New("slots").Parse(string(tmplContent)))

	out, err := os.Create("slots.sql")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "-- Code generated by gen_slots.go. DO NOT EDIT.")
	fmt.Fprintln(out, "-- Edit slots_template.sql.tmpl or slots_shared.sql.part instead.")
	fmt.Fprintln(out, "-- Regenerate: go generate ./internal/database/queries/")
	fmt.Fprintln(out)

	shared, err := os.ReadFile("slots_shared.sql.part")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading shared queries: %v\n", err)
		os.Exit(1)
	}
	out.Write(shared)
	fmt.Fprintln(out)

	for _, e := range entities {
		if err := tmpl.Execute(out, e); err != nil {
			fmt.Fprintf(os.Stderr, "Error executing template for %s: %v\n", e.EntityType, err)
			os.Exit(1)
		}
		fmt.Fprintln(out)
	}
}
