version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  default: none
  enable:
    # Correctness
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    # Style
    - misspell
    - revive
    # Complexity
    - gocyclo
    - gocognit
    - funlen
    - nestif
    # Quality
    - unconvert
    - goconst
    - unparam
    - gocritic
    # Error handling
    - nilerr
    - errname
    - errorlint
    # Reliability
    - bodyclose
    - noctx
    - nakedret
    - nilnil
    # Readability
    - usestdlibvars
    # Testing
    - thelper
    # Safety
    - gosec

  settings:
    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gocyclo:
      min-complexity: 10

    gocognit:
      min-complexity: 15

    nestif:
      min-complexity: 5

    nakedret:
      max-func-lines: 30

    goconst:
      min-len: 3
      min-occurrences: 3
      ignore-calls: true

    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: var-declaration
        - name: var-naming

    errorlint:
      errorf: true
      asserts: true
      comparison: true

    gosec:
      excludes:
        - G104
        - G304

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "err" shadows'
      - path: _test\.go
        linters:
          - funlen
          - gocyclo
          - gocognit
          - goconst
          - errcheck
          - gosec
          - nestif
      - path: cmd/
        linters:
          - funlen
          - gocyclo
          - gocognit
      - path: mock/
        linters:
          - funlen
          - goconst
          - unparam
      - path: internal/api/server\.go
        linters:
          - funlen
          - gocyclo
          - gocognit
      - linters:
          - revive
        text: 'var-naming: avoid (package names|meaningless)'
    paths:
      - internal/database/sqlc
      - internal/database/migrations

formatters:
  enable:
    - goimports
  exclusions:
    generated: strict
    paths:
      - internal/database/sqlc
      - internal/database/migrations

output:
  formats:
    colored-line-number:
      path: stdout
  sort-results: true
  sort-order:
    - linter
    - file
  show-stats: true
