version: 2

project_name: slipstream

before:
  hooks:
    - go mod tidy
    - bun install --cwd web
    - bun run --cwd web build

builds:
  # Windows build with CGO (for walk/systray)
  - id: slipstream-windows
    main: ./cmd/slipstream
    binary: slipstream
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    ldflags:
      - -s -w
      - -H windowsgui
      - -X 'github.com/slipstream/slipstream/internal/config.Version={{.Version}}'
      - -X 'github.com/slipstream/slipstream/internal/config.EmbeddedTMDBKey={{.Env.TMDB_API_KEY}}'
      - -X 'github.com/slipstream/slipstream/internal/config.EmbeddedTVDBKey={{.Env.TVDB_API_KEY}}'
      - -X 'github.com/slipstream/slipstream/internal/config.EmbeddedOMDBKey={{.Env.OMDB_API_KEY}}'

  # Linux builds without CGO
  - id: slipstream-linux
    main: ./cmd/slipstream
    binary: slipstream
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/slipstream/slipstream/internal/config.Version={{.Version}}'
      - -X 'github.com/slipstream/slipstream/internal/config.EmbeddedTMDBKey={{.Env.TMDB_API_KEY}}'
      - -X 'github.com/slipstream/slipstream/internal/config.EmbeddedTVDBKey={{.Env.TVDB_API_KEY}}'
      - -X 'github.com/slipstream/slipstream/internal/config.EmbeddedOMDBKey={{.Env.OMDB_API_KEY}}'

  # macOS builds are done natively in CI/CD with CGO for menu bar support

archives:
  # Windows portable ZIP only
  - id: windows-zip
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - slipstream-windows
    files:
      - README*
    wrap_in_directory: false

nfpms:
  - id: packages
    package_name: slipstream
    vendor: SlipStream
    homepage: https://github.com/jatassi/SlipStream
    maintainer: SlipStream <noreply@slipstream.local>
    description: Unified media management system
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    scripts:
      postinstall: "scripts/linux/postinstall.sh"
    builds:
      - slipstream-linux

checksum:
  name_template: 'checksums.txt'

changelog:
  disable: true

release:
  disable: true
