export { autosearchApi } from './autosearch'
export { calendarApi } from './calendar'
export { apiFetch, buildQueryString } from './client'
export { defaultsApi } from './defaults'
export { downloadClientsApi } from './download-clients'
export { filesystemApi } from './filesystem'
export { healthApi } from './health'
export { historyApi } from './history'
export { indexersApi } from './indexers'
export { libraryApi } from './library'
export { logsApi } from './logs'
export { metadataApi } from './metadata'
export { missingApi } from './missing'
export { moviesApi } from './movies'
export { notificationsApi } from './notifications'
export { prowlarrApi } from './prowlarr'
export { qualityProfilesApi } from './quality-profiles'
export { queueApi } from './queue'
export { rootFoldersApi } from './root-folders'
export { rssSyncApi } from './rsssync'
export { schedulerApi } from './scheduler'
export { searchApi } from './search'
export { seriesApi } from './series'
export { slotsApi } from './slots'
export { systemApi } from './system'
export { updateApi } from './update'

// Portal APIs
export * from './portal'

// Admin APIs
export * as adminApi from './admin'

// Auth APIs
export * as authApi from './auth'
