// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_mappings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearDownloadMappingSlot = `-- name: ClearDownloadMappingSlot :exec
UPDATE download_mappings SET target_slot_id = NULL
WHERE client_id = ? AND download_id = ?
`

type ClearDownloadMappingSlotParams struct {
	ClientID   int64  `json:"client_id"`
	DownloadID string `json:"download_id"`
}

// Req 10.2.1: Clear slot when download fails or is rejected
func (q *Queries) ClearDownloadMappingSlot(ctx context.Context, arg ClearDownloadMappingSlotParams) error {
	_, err := q.db.ExecContext(ctx, clearDownloadMappingSlot, arg.ClientID, arg.DownloadID)
	return err
}

const createDownloadMapping = `-- name: CreateDownloadMapping :one
INSERT INTO download_mappings (
    client_id, download_id, module_type, entity_type, entity_id, season_number,
    is_season_pack, is_complete_series, target_slot_id, source
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (client_id, download_id) DO UPDATE SET
    module_type = excluded.module_type,
    entity_type = excluded.entity_type,
    entity_id = excluded.entity_id,
    season_number = excluded.season_number,
    is_season_pack = excluded.is_season_pack,
    is_complete_series = excluded.is_complete_series,
    target_slot_id = excluded.target_slot_id,
    source = excluded.source,
    import_attempts = 0,
    last_import_error = NULL,
    next_import_retry_at = NULL
RETURNING id, client_id, download_id, module_type, entity_type, entity_id, season_number, is_season_pack, is_complete_series, target_slot_id, source, import_attempts, last_import_error, next_import_retry_at, created_at
`

type CreateDownloadMappingParams struct {
	ClientID         int64         `json:"client_id"`
	DownloadID       string        `json:"download_id"`
	ModuleType       string        `json:"module_type"`
	EntityType       string        `json:"entity_type"`
	EntityID         int64         `json:"entity_id"`
	SeasonNumber     sql.NullInt64 `json:"season_number"`
	IsSeasonPack     bool          `json:"is_season_pack"`
	IsCompleteSeries bool          `json:"is_complete_series"`
	TargetSlotID     sql.NullInt64 `json:"target_slot_id"`
	Source           string        `json:"source"`
}

func (q *Queries) CreateDownloadMapping(ctx context.Context, arg CreateDownloadMappingParams) (*DownloadMapping, error) {
	row := q.db.QueryRowContext(ctx, createDownloadMapping,
		arg.ClientID,
		arg.DownloadID,
		arg.ModuleType,
		arg.EntityType,
		arg.EntityID,
		arg.SeasonNumber,
		arg.IsSeasonPack,
		arg.IsCompleteSeries,
		arg.TargetSlotID,
		arg.Source,
	)
	var i DownloadMapping
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DownloadID,
		&i.ModuleType,
		&i.EntityType,
		&i.EntityID,
		&i.SeasonNumber,
		&i.IsSeasonPack,
		&i.IsCompleteSeries,
		&i.TargetSlotID,
		&i.Source,
		&i.ImportAttempts,
		&i.LastImportError,
		&i.NextImportRetryAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteDownloadMapping = `-- name: DeleteDownloadMapping :exec
DELETE FROM download_mappings
WHERE client_id = ? AND download_id = ?
`

type DeleteDownloadMappingParams struct {
	ClientID   int64  `json:"client_id"`
	DownloadID string `json:"download_id"`
}

func (q *Queries) DeleteDownloadMapping(ctx context.Context, arg DeleteDownloadMappingParams) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadMapping, arg.ClientID, arg.DownloadID)
	return err
}

const deleteDownloadMappingsByEntity = `-- name: DeleteDownloadMappingsByEntity :exec
DELETE FROM download_mappings
WHERE module_type = ? AND entity_type = ? AND entity_id = ?
`

type DeleteDownloadMappingsByEntityParams struct {
	ModuleType string `json:"module_type"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

// Clean up download mappings when an entity is deleted
func (q *Queries) DeleteDownloadMappingsByEntity(ctx context.Context, arg DeleteDownloadMappingsByEntityParams) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadMappingsByEntity, arg.ModuleType, arg.EntityType, arg.EntityID)
	return err
}

const deleteOldDownloadMappings = `-- name: DeleteOldDownloadMappings :exec
DELETE FROM download_mappings
WHERE created_at < datetime('now', '-7 days')
`

func (q *Queries) DeleteOldDownloadMappings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldDownloadMappings)
	return err
}

const getDownloadMapping = `-- name: GetDownloadMapping :one
SELECT id, client_id, download_id, module_type, entity_type, entity_id, season_number, is_season_pack, is_complete_series, target_slot_id, source, import_attempts, last_import_error, next_import_retry_at, created_at FROM download_mappings
WHERE client_id = ? AND download_id = ?
`

type GetDownloadMappingParams struct {
	ClientID   int64  `json:"client_id"`
	DownloadID string `json:"download_id"`
}

func (q *Queries) GetDownloadMapping(ctx context.Context, arg GetDownloadMappingParams) (*DownloadMapping, error) {
	row := q.db.QueryRowContext(ctx, getDownloadMapping, arg.ClientID, arg.DownloadID)
	var i DownloadMapping
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DownloadID,
		&i.ModuleType,
		&i.EntityType,
		&i.EntityID,
		&i.SeasonNumber,
		&i.IsSeasonPack,
		&i.IsCompleteSeries,
		&i.TargetSlotID,
		&i.Source,
		&i.ImportAttempts,
		&i.LastImportError,
		&i.NextImportRetryAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getDownloadMappingsByClientDownloadIDs = `-- name: GetDownloadMappingsByClientDownloadIDs :many
SELECT id, client_id, download_id, module_type, entity_type, entity_id, season_number, is_season_pack, is_complete_series, target_slot_id, source, import_attempts, last_import_error, next_import_retry_at, created_at FROM download_mappings
WHERE (client_id, download_id) IN (/*SLICE:client_download_ids*//*SLICE:client_download_ids*/?)
`

func (q *Queries) GetDownloadMappingsByClientDownloadIDs(ctx context.Context) ([]*DownloadMapping, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadMappingsByClientDownloadIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DownloadMapping{}
	for rows.Next() {
		var i DownloadMapping
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DownloadID,
			&i.ModuleType,
			&i.EntityType,
			&i.EntityID,
			&i.SeasonNumber,
			&i.IsSeasonPack,
			&i.IsCompleteSeries,
			&i.TargetSlotID,
			&i.Source,
			&i.ImportAttempts,
			&i.LastImportError,
			&i.NextImportRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadMappingsBySlot = `-- name: GetDownloadMappingsBySlot :many
SELECT id, client_id, download_id, module_type, entity_type, entity_id, season_number, is_season_pack, is_complete_series, target_slot_id, source, import_attempts, last_import_error, next_import_retry_at, created_at FROM download_mappings
WHERE target_slot_id = ?
ORDER BY created_at DESC
`

// Get all mappings targeting a specific slot
func (q *Queries) GetDownloadMappingsBySlot(ctx context.Context, targetSlotID sql.NullInt64) ([]*DownloadMapping, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadMappingsBySlot, targetSlotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DownloadMapping{}
	for rows.Next() {
		var i DownloadMapping
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DownloadID,
			&i.ModuleType,
			&i.EntityType,
			&i.EntityID,
			&i.SeasonNumber,
			&i.IsSeasonPack,
			&i.IsCompleteSeries,
			&i.TargetSlotID,
			&i.Source,
			&i.ImportAttempts,
			&i.LastImportError,
			&i.NextImportRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadingEntityData = `-- name: GetDownloadingEntityData :many
SELECT DISTINCT entity_type, entity_id, season_number, is_season_pack, is_complete_series
FROM download_mappings
WHERE module_type = ?
`

type GetDownloadingEntityDataRow struct {
	EntityType       string        `json:"entity_type"`
	EntityID         int64         `json:"entity_id"`
	SeasonNumber     sql.NullInt64 `json:"season_number"`
	IsSeasonPack     bool          `json:"is_season_pack"`
	IsCompleteSeries bool          `json:"is_complete_series"`
}

func (q *Queries) GetDownloadingEntityData(ctx context.Context, moduleType string) ([]*GetDownloadingEntityDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadingEntityData, moduleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDownloadingEntityDataRow{}
	for rows.Next() {
		var i GetDownloadingEntityDataRow
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.SeasonNumber,
			&i.IsSeasonPack,
			&i.IsCompleteSeries,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadingEntityIDs = `-- name: GetDownloadingEntityIDs :many
SELECT DISTINCT entity_id FROM download_mappings
WHERE module_type = ? AND entity_type = ?
`

type GetDownloadingEntityIDsParams struct {
	ModuleType string `json:"module_type"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetDownloadingEntityIDs(ctx context.Context, arg GetDownloadingEntityIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadingEntityIDs, arg.ModuleType, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var entity_id int64
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDownloadMappingAttempts = `-- name: IncrementDownloadMappingAttempts :one
UPDATE download_mappings
SET import_attempts = import_attempts + 1,
    last_import_error = ?,
    next_import_retry_at = ?
WHERE client_id = ? AND download_id = ?
RETURNING import_attempts
`

type IncrementDownloadMappingAttemptsParams struct {
	LastImportError   sql.NullString `json:"last_import_error"`
	NextImportRetryAt sql.NullTime   `json:"next_import_retry_at"`
	ClientID          int64          `json:"client_id"`
	DownloadID        string         `json:"download_id"`
}

func (q *Queries) IncrementDownloadMappingAttempts(ctx context.Context, arg IncrementDownloadMappingAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementDownloadMappingAttempts,
		arg.LastImportError,
		arg.NextImportRetryAt,
		arg.ClientID,
		arg.DownloadID,
	)
	var import_attempts int64
	err := row.Scan(&import_attempts)
	return import_attempts, err
}

const isEntityDownloading = `-- name: IsEntityDownloading :one
SELECT EXISTS(
    SELECT 1 FROM download_mappings
    WHERE module_type = ? AND entity_type = ? AND entity_id = ?
) AS downloading
`

type IsEntityDownloadingParams struct {
	ModuleType string `json:"module_type"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) IsEntityDownloading(ctx context.Context, arg IsEntityDownloadingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isEntityDownloading, arg.ModuleType, arg.EntityType, arg.EntityID)
	var downloading int64
	err := row.Scan(&downloading)
	return downloading, err
}

const listActiveDownloadMappings = `-- name: ListActiveDownloadMappings :many
SELECT id, client_id, download_id, module_type, entity_type, entity_id, season_number, is_season_pack, is_complete_series, target_slot_id, source, import_attempts, last_import_error, next_import_retry_at, created_at FROM download_mappings
ORDER BY created_at DESC
`

func (q *Queries) ListActiveDownloadMappings(ctx context.Context) ([]*DownloadMapping, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDownloadMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*DownloadMapping{}
	for rows.Next() {
		var i DownloadMapping
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DownloadID,
			&i.ModuleType,
			&i.EntityType,
			&i.EntityID,
			&i.SeasonNumber,
			&i.IsSeasonPack,
			&i.IsCompleteSeries,
			&i.TargetSlotID,
			&i.Source,
			&i.ImportAttempts,
			&i.LastImportError,
			&i.NextImportRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
