// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Auth struct {
	ID           int64        `json:"id"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type AutosearchStatus struct {
	ID               int64        `json:"id"`
	ItemType         string       `json:"item_type"`
	ItemID           int64        `json:"item_id"`
	FailureCount     int64        `json:"failure_count"`
	LastSearchedAt   sql.NullTime `json:"last_searched_at"`
	LastMetaChangeAt sql.NullTime `json:"last_meta_change_at"`
}

type DefinitionMetadatum struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Privacy     sql.NullString `json:"privacy"`
	Language    sql.NullString `json:"language"`
	Protocol    sql.NullString `json:"protocol"`
	CachedAt    sql.NullTime   `json:"cached_at"`
	FilePath    sql.NullString `json:"file_path"`
}

type Download struct {
	ID          int64          `json:"id"`
	ClientID    sql.NullInt64  `json:"client_id"`
	ExternalID  sql.NullString `json:"external_id"`
	Title       string         `json:"title"`
	MediaType   string         `json:"media_type"`
	MediaID     int64          `json:"media_id"`
	Status      string         `json:"status"`
	Progress    float64        `json:"progress"`
	Size        int64          `json:"size"`
	DownloadUrl sql.NullString `json:"download_url"`
	OutputPath  sql.NullString `json:"output_path"`
	AddedAt     sql.NullTime   `json:"added_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type DownloadClient struct {
	ID                 int64           `json:"id"`
	Name               string          `json:"name"`
	Type               string          `json:"type"`
	Host               string          `json:"host"`
	Port               int64           `json:"port"`
	Username           sql.NullString  `json:"username"`
	Password           sql.NullString  `json:"password"`
	UseSsl             int64           `json:"use_ssl"`
	Category           sql.NullString  `json:"category"`
	Priority           int64           `json:"priority"`
	Enabled            int64           `json:"enabled"`
	CreatedAt          sql.NullTime    `json:"created_at"`
	UpdatedAt          sql.NullTime    `json:"updated_at"`
	ImportDelaySeconds int64           `json:"import_delay_seconds"`
	CleanupMode        string          `json:"cleanup_mode"`
	SeedRatioTarget    sql.NullFloat64 `json:"seed_ratio_target"`
}

type DownloadMapping struct {
	ID               int64         `json:"id"`
	ClientID         int64         `json:"client_id"`
	DownloadID       string        `json:"download_id"`
	MovieID          sql.NullInt64 `json:"movie_id"`
	SeriesID         sql.NullInt64 `json:"series_id"`
	SeasonNumber     sql.NullInt64 `json:"season_number"`
	EpisodeID        sql.NullInt64 `json:"episode_id"`
	IsSeasonPack     int64         `json:"is_season_pack"`
	IsCompleteSeries int64         `json:"is_complete_series"`
	CreatedAt        time.Time     `json:"created_at"`
	TargetSlotID     sql.NullInt64 `json:"target_slot_id"`
}

type Episode struct {
	ID            int64          `json:"id"`
	SeriesID      int64          `json:"series_id"`
	SeasonNumber  int64          `json:"season_number"`
	EpisodeNumber int64          `json:"episode_number"`
	Title         sql.NullString `json:"title"`
	Overview      sql.NullString `json:"overview"`
	AirDate       sql.NullTime   `json:"air_date"`
	Monitored     int64          `json:"monitored"`
	Released      int64          `json:"released"`
}

type EpisodeFile struct {
	ID               int64          `json:"id"`
	EpisodeID        int64          `json:"episode_id"`
	Path             string         `json:"path"`
	Size             int64          `json:"size"`
	Quality          sql.NullString `json:"quality"`
	VideoCodec       sql.NullString `json:"video_codec"`
	AudioCodec       sql.NullString `json:"audio_codec"`
	Resolution       sql.NullString `json:"resolution"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	QualityID        sql.NullInt64  `json:"quality_id"`
	OriginalPath     sql.NullString `json:"original_path"`
	OriginalFilename sql.NullString `json:"original_filename"`
	ImportedAt       sql.NullTime   `json:"imported_at"`
	SlotID           sql.NullInt64  `json:"slot_id"`
}

type EpisodeSlotAssignment struct {
	ID        int64         `json:"id"`
	EpisodeID int64         `json:"episode_id"`
	SlotID    int64         `json:"slot_id"`
	FileID    sql.NullInt64 `json:"file_id"`
	Monitored int64         `json:"monitored"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type History struct {
	ID        int64          `json:"id"`
	EventType string         `json:"event_type"`
	MediaType string         `json:"media_type"`
	MediaID   int64          `json:"media_id"`
	Source    sql.NullString `json:"source"`
	Quality   sql.NullString `json:"quality"`
	Data      sql.NullString `json:"data"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ImportSetting struct {
	ID                       int64          `json:"id"`
	ValidationLevel          string         `json:"validation_level"`
	MinimumFileSizeMb        int64          `json:"minimum_file_size_mb"`
	VideoExtensions          string         `json:"video_extensions"`
	MatchConflictBehavior    string         `json:"match_conflict_behavior"`
	UnknownMediaBehavior     string         `json:"unknown_media_behavior"`
	RenameEpisodes           bool           `json:"rename_episodes"`
	ReplaceIllegalCharacters bool           `json:"replace_illegal_characters"`
	ColonReplacement         string         `json:"colon_replacement"`
	CustomColonReplacement   sql.NullString `json:"custom_colon_replacement"`
	StandardEpisodeFormat    string         `json:"standard_episode_format"`
	DailyEpisodeFormat       string         `json:"daily_episode_format"`
	AnimeEpisodeFormat       string         `json:"anime_episode_format"`
	SeriesFolderFormat       string         `json:"series_folder_format"`
	SeasonFolderFormat       string         `json:"season_folder_format"`
	SpecialsFolderFormat     string         `json:"specials_folder_format"`
	MultiEpisodeStyle        string         `json:"multi_episode_style"`
	RenameMovies             bool           `json:"rename_movies"`
	MovieFolderFormat        string         `json:"movie_folder_format"`
	MovieFileFormat          string         `json:"movie_file_format"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type Indexer struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	DefinitionID      string         `json:"definition_id"`
	Settings          sql.NullString `json:"settings"`
	Categories        sql.NullString `json:"categories"`
	SupportsMovies    int64          `json:"supports_movies"`
	SupportsTv        int64          `json:"supports_tv"`
	Priority          int64          `json:"priority"`
	Enabled           int64          `json:"enabled"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	AutoSearchEnabled int64          `json:"auto_search_enabled"`
}

type IndexerHistory struct {
	ID           int64          `json:"id"`
	IndexerID    int64          `json:"indexer_id"`
	EventType    string         `json:"event_type"`
	Successful   int64          `json:"successful"`
	Query        sql.NullString `json:"query"`
	Categories   sql.NullString `json:"categories"`
	ResultsCount sql.NullInt64  `json:"results_count"`
	ElapsedMs    sql.NullInt64  `json:"elapsed_ms"`
	Data         sql.NullString `json:"data"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type IndexerStatus struct {
	ID                int64          `json:"id"`
	IndexerID         int64          `json:"indexer_id"`
	InitialFailure    sql.NullTime   `json:"initial_failure"`
	MostRecentFailure sql.NullTime   `json:"most_recent_failure"`
	EscalationLevel   sql.NullInt64  `json:"escalation_level"`
	DisabledTill      sql.NullTime   `json:"disabled_till"`
	LastRssSync       sql.NullTime   `json:"last_rss_sync"`
	Cookies           sql.NullString `json:"cookies"`
	CookiesExpiration sql.NullTime   `json:"cookies_expiration"`
}

type Job struct {
	ID              string       `json:"id"`
	Name            string       `json:"name"`
	LastRun         sql.NullTime `json:"last_run"`
	NextRun         sql.NullTime `json:"next_run"`
	IntervalSeconds int64        `json:"interval_seconds"`
	Enabled         int64        `json:"enabled"`
}

type Movie struct {
	ID                  int64          `json:"id"`
	Title               string         `json:"title"`
	SortTitle           string         `json:"sort_title"`
	Year                sql.NullInt64  `json:"year"`
	TmdbID              sql.NullInt64  `json:"tmdb_id"`
	ImdbID              sql.NullString `json:"imdb_id"`
	Overview            sql.NullString `json:"overview"`
	Runtime             sql.NullInt64  `json:"runtime"`
	Path                sql.NullString `json:"path"`
	RootFolderID        sql.NullInt64  `json:"root_folder_id"`
	QualityProfileID    sql.NullInt64  `json:"quality_profile_id"`
	Monitored           int64          `json:"monitored"`
	Status              string         `json:"status"`
	AddedAt             sql.NullTime   `json:"added_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	ReleaseDate         sql.NullTime   `json:"release_date"`
	DigitalReleaseDate  sql.NullTime   `json:"digital_release_date"`
	PhysicalReleaseDate sql.NullTime   `json:"physical_release_date"`
	Released            int64          `json:"released"`
	AvailabilityStatus  string         `json:"availability_status"`
}

type MovieFile struct {
	ID               int64          `json:"id"`
	MovieID          int64          `json:"movie_id"`
	Path             string         `json:"path"`
	Size             int64          `json:"size"`
	Quality          sql.NullString `json:"quality"`
	VideoCodec       sql.NullString `json:"video_codec"`
	AudioCodec       sql.NullString `json:"audio_codec"`
	Resolution       sql.NullString `json:"resolution"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	QualityID        sql.NullInt64  `json:"quality_id"`
	OriginalPath     sql.NullString `json:"original_path"`
	OriginalFilename sql.NullString `json:"original_filename"`
	ImportedAt       sql.NullTime   `json:"imported_at"`
	SlotID           sql.NullInt64  `json:"slot_id"`
}

type MovieSlotAssignment struct {
	ID        int64         `json:"id"`
	MovieID   int64         `json:"movie_id"`
	SlotID    int64         `json:"slot_id"`
	FileID    sql.NullInt64 `json:"file_id"`
	Monitored int64         `json:"monitored"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type MultiVersionSetting struct {
	ID              int64        `json:"id"`
	Enabled         int64        `json:"enabled"`
	DryRunCompleted int64        `json:"dry_run_completed"`
	LastMigrationAt sql.NullTime `json:"last_migration_at"`
	CreatedAt       sql.NullTime `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type QualityProfile struct {
	ID                   int64        `json:"id"`
	Name                 string       `json:"name"`
	Cutoff               int64        `json:"cutoff"`
	Items                string       `json:"items"`
	CreatedAt            sql.NullTime `json:"created_at"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
	HdrSettings          string       `json:"hdr_settings"`
	VideoCodecSettings   string       `json:"video_codec_settings"`
	AudioCodecSettings   string       `json:"audio_codec_settings"`
	AudioChannelSettings string       `json:"audio_channel_settings"`
}

type QueueMedium struct {
	ID                int64          `json:"id"`
	DownloadMappingID int64          `json:"download_mapping_id"`
	EpisodeID         sql.NullInt64  `json:"episode_id"`
	MovieID           sql.NullInt64  `json:"movie_id"`
	FilePath          sql.NullString `json:"file_path"`
	FileStatus        string         `json:"file_status"`
	ErrorMessage      sql.NullString `json:"error_message"`
	ImportAttempts    int64          `json:"import_attempts"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	TargetSlotID      sql.NullInt64  `json:"target_slot_id"`
}

type RootFolder struct {
	ID        int64         `json:"id"`
	Path      string        `json:"path"`
	Name      string        `json:"name"`
	MediaType string        `json:"media_type"`
	FreeSpace sql.NullInt64 `json:"free_space"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Season struct {
	ID           int64          `json:"id"`
	SeriesID     int64          `json:"series_id"`
	SeasonNumber int64          `json:"season_number"`
	Monitored    int64          `json:"monitored"`
	Overview     sql.NullString `json:"overview"`
	PosterUrl    sql.NullString `json:"poster_url"`
	Released     int64          `json:"released"`
}

type Series struct {
	ID                 int64          `json:"id"`
	Title              string         `json:"title"`
	SortTitle          string         `json:"sort_title"`
	Year               sql.NullInt64  `json:"year"`
	TvdbID             sql.NullInt64  `json:"tvdb_id"`
	TmdbID             sql.NullInt64  `json:"tmdb_id"`
	ImdbID             sql.NullString `json:"imdb_id"`
	Overview           sql.NullString `json:"overview"`
	Runtime            sql.NullInt64  `json:"runtime"`
	Path               sql.NullString `json:"path"`
	RootFolderID       sql.NullInt64  `json:"root_folder_id"`
	QualityProfileID   sql.NullInt64  `json:"quality_profile_id"`
	Monitored          int64          `json:"monitored"`
	SeasonFolder       int64          `json:"season_folder"`
	Status             string         `json:"status"`
	AddedAt            sql.NullTime   `json:"added_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	Network            sql.NullString `json:"network"`
	Released           int64          `json:"released"`
	AvailabilityStatus string         `json:"availability_status"`
	FormatType         sql.NullString `json:"format_type"`
}

type Setting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type VersionSlot struct {
	ID                int64         `json:"id"`
	SlotNumber        int64         `json:"slot_number"`
	Name              string        `json:"name"`
	Enabled           int64         `json:"enabled"`
	QualityProfileID  sql.NullInt64 `json:"quality_profile_id"`
	DisplayOrder      int64         `json:"display_order"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
	MovieRootFolderID sql.NullInt64 `json:"movie_root_folder_id"`
	TvRootFolderID    sql.NullInt64 `json:"tv_root_folder_id"`
}
