// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Auth struct {
	ID           int64        `json:"id"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type AutosearchStatus struct {
	ID               int64        `json:"id"`
	ItemType         string       `json:"item_type"`
	ItemID           int64        `json:"item_id"`
	SearchType       string       `json:"search_type"`
	FailureCount     int64        `json:"failure_count"`
	LastSearchedAt   sql.NullTime `json:"last_searched_at"`
	LastMetaChangeAt sql.NullTime `json:"last_meta_change_at"`
}

type DefinitionMetadatum struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Privacy     sql.NullString `json:"privacy"`
	Language    sql.NullString `json:"language"`
	Protocol    sql.NullString `json:"protocol"`
	CachedAt    sql.NullTime   `json:"cached_at"`
	FilePath    sql.NullString `json:"file_path"`
}

type Download struct {
	ID          int64          `json:"id"`
	ClientID    sql.NullInt64  `json:"client_id"`
	ExternalID  sql.NullString `json:"external_id"`
	Title       string         `json:"title"`
	MediaType   string         `json:"media_type"`
	MediaID     int64          `json:"media_id"`
	Status      string         `json:"status"`
	Progress    float64        `json:"progress"`
	Size        int64          `json:"size"`
	DownloadUrl sql.NullString `json:"download_url"`
	OutputPath  sql.NullString `json:"output_path"`
	AddedAt     sql.NullTime   `json:"added_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type DownloadClient struct {
	ID                 int64           `json:"id"`
	Name               string          `json:"name"`
	Type               string          `json:"type"`
	Host               string          `json:"host"`
	Port               int64           `json:"port"`
	Username           sql.NullString  `json:"username"`
	Password           sql.NullString  `json:"password"`
	UseSsl             int64           `json:"use_ssl"`
	Category           sql.NullString  `json:"category"`
	Priority           int64           `json:"priority"`
	Enabled            int64           `json:"enabled"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ImportDelaySeconds int64           `json:"import_delay_seconds"`
	CleanupMode        string          `json:"cleanup_mode"`
	SeedRatioTarget    sql.NullFloat64 `json:"seed_ratio_target"`
}

type DownloadMapping struct {
	ID               int64         `json:"id"`
	ClientID         int64         `json:"client_id"`
	DownloadID       string        `json:"download_id"`
	MovieID          sql.NullInt64 `json:"movie_id"`
	SeriesID         sql.NullInt64 `json:"series_id"`
	SeasonNumber     sql.NullInt64 `json:"season_number"`
	EpisodeID        sql.NullInt64 `json:"episode_id"`
	IsSeasonPack     int64         `json:"is_season_pack"`
	IsCompleteSeries int64         `json:"is_complete_series"`
	CreatedAt        time.Time     `json:"created_at"`
	TargetSlotID     sql.NullInt64 `json:"target_slot_id"`
	Source           string        `json:"source"`
}

type Episode struct {
	ID               int64          `json:"id"`
	SeriesID         int64          `json:"series_id"`
	SeasonNumber     int64          `json:"season_number"`
	EpisodeNumber    int64          `json:"episode_number"`
	Title            sql.NullString `json:"title"`
	Overview         sql.NullString `json:"overview"`
	AirDate          sql.NullTime   `json:"air_date"`
	Monitored        int64          `json:"monitored"`
	Status           string         `json:"status"`
	ActiveDownloadID sql.NullString `json:"active_download_id"`
	StatusMessage    sql.NullString `json:"status_message"`
}

type EpisodeFile struct {
	ID               int64          `json:"id"`
	EpisodeID        int64          `json:"episode_id"`
	Path             string         `json:"path"`
	Size             int64          `json:"size"`
	Quality          sql.NullString `json:"quality"`
	VideoCodec       sql.NullString `json:"video_codec"`
	AudioCodec       sql.NullString `json:"audio_codec"`
	Resolution       sql.NullString `json:"resolution"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	QualityID        sql.NullInt64  `json:"quality_id"`
	OriginalPath     sql.NullString `json:"original_path"`
	OriginalFilename sql.NullString `json:"original_filename"`
	ImportedAt       sql.NullTime   `json:"imported_at"`
	SlotID           sql.NullInt64  `json:"slot_id"`
	AudioChannels    sql.NullString `json:"audio_channels"`
	DynamicRange     sql.NullString `json:"dynamic_range"`
}

type EpisodeSlotAssignment struct {
	ID               int64          `json:"id"`
	EpisodeID        int64          `json:"episode_id"`
	SlotID           int64          `json:"slot_id"`
	FileID           sql.NullInt64  `json:"file_id"`
	Monitored        int64          `json:"monitored"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	Status           string         `json:"status"`
	ActiveDownloadID sql.NullString `json:"active_download_id"`
	StatusMessage    sql.NullString `json:"status_message"`
}

type History struct {
	ID        int64          `json:"id"`
	EventType string         `json:"event_type"`
	MediaType string         `json:"media_type"`
	MediaID   int64          `json:"media_id"`
	Source    sql.NullString `json:"source"`
	Quality   sql.NullString `json:"quality"`
	Data      sql.NullString `json:"data"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ImportDecision struct {
	ID                 int64          `json:"id"`
	SourcePath         string         `json:"source_path"`
	Decision           string         `json:"decision"`
	MediaType          string         `json:"media_type"`
	MediaID            int64          `json:"media_id"`
	SlotID             sql.NullInt64  `json:"slot_id"`
	CandidateQualityID sql.NullInt64  `json:"candidate_quality_id"`
	ExistingQualityID  sql.NullInt64  `json:"existing_quality_id"`
	ExistingFileID     sql.NullInt64  `json:"existing_file_id"`
	QualityProfileID   sql.NullInt64  `json:"quality_profile_id"`
	Reason             sql.NullString `json:"reason"`
	EvaluatedAt        time.Time      `json:"evaluated_at"`
}

type ImportSetting struct {
	ID                       int64          `json:"id"`
	ValidationLevel          string         `json:"validation_level"`
	MinimumFileSizeMb        int64          `json:"minimum_file_size_mb"`
	VideoExtensions          string         `json:"video_extensions"`
	MatchConflictBehavior    string         `json:"match_conflict_behavior"`
	UnknownMediaBehavior     string         `json:"unknown_media_behavior"`
	RenameEpisodes           bool           `json:"rename_episodes"`
	ReplaceIllegalCharacters bool           `json:"replace_illegal_characters"`
	ColonReplacement         string         `json:"colon_replacement"`
	CustomColonReplacement   sql.NullString `json:"custom_colon_replacement"`
	StandardEpisodeFormat    string         `json:"standard_episode_format"`
	DailyEpisodeFormat       string         `json:"daily_episode_format"`
	AnimeEpisodeFormat       string         `json:"anime_episode_format"`
	SeriesFolderFormat       string         `json:"series_folder_format"`
	SeasonFolderFormat       string         `json:"season_folder_format"`
	SpecialsFolderFormat     string         `json:"specials_folder_format"`
	MultiEpisodeStyle        string         `json:"multi_episode_style"`
	RenameMovies             bool           `json:"rename_movies"`
	MovieFolderFormat        string         `json:"movie_folder_format"`
	MovieFileFormat          string         `json:"movie_file_format"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type Indexer struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	DefinitionID      string         `json:"definition_id"`
	Settings          sql.NullString `json:"settings"`
	Categories        sql.NullString `json:"categories"`
	SupportsMovies    int64          `json:"supports_movies"`
	SupportsTv        int64          `json:"supports_tv"`
	Priority          int64          `json:"priority"`
	Enabled           int64          `json:"enabled"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	AutoSearchEnabled int64          `json:"auto_search_enabled"`
	RssEnabled        int64          `json:"rss_enabled"`
}

type IndexerHistory struct {
	ID           int64          `json:"id"`
	IndexerID    int64          `json:"indexer_id"`
	EventType    string         `json:"event_type"`
	Successful   int64          `json:"successful"`
	Query        sql.NullString `json:"query"`
	Categories   sql.NullString `json:"categories"`
	ResultsCount sql.NullInt64  `json:"results_count"`
	ElapsedMs    sql.NullInt64  `json:"elapsed_ms"`
	Data         sql.NullString `json:"data"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type IndexerStatus struct {
	ID                 int64          `json:"id"`
	IndexerID          int64          `json:"indexer_id"`
	InitialFailure     sql.NullTime   `json:"initial_failure"`
	MostRecentFailure  sql.NullTime   `json:"most_recent_failure"`
	EscalationLevel    sql.NullInt64  `json:"escalation_level"`
	DisabledTill       sql.NullTime   `json:"disabled_till"`
	LastRssSync        sql.NullTime   `json:"last_rss_sync"`
	Cookies            sql.NullString `json:"cookies"`
	CookiesExpiration  sql.NullTime   `json:"cookies_expiration"`
	LastRssReleaseUrl  sql.NullString `json:"last_rss_release_url"`
	LastRssReleaseDate sql.NullTime   `json:"last_rss_release_date"`
}

type Job struct {
	ID              string       `json:"id"`
	Name            string       `json:"name"`
	LastRun         sql.NullTime `json:"last_run"`
	NextRun         sql.NullTime `json:"next_run"`
	IntervalSeconds int64        `json:"interval_seconds"`
	Enabled         int64        `json:"enabled"`
}

type Movie struct {
	ID                    int64          `json:"id"`
	Title                 string         `json:"title"`
	SortTitle             string         `json:"sort_title"`
	Year                  sql.NullInt64  `json:"year"`
	TmdbID                sql.NullInt64  `json:"tmdb_id"`
	ImdbID                sql.NullString `json:"imdb_id"`
	Overview              sql.NullString `json:"overview"`
	Runtime               sql.NullInt64  `json:"runtime"`
	Path                  sql.NullString `json:"path"`
	RootFolderID          sql.NullInt64  `json:"root_folder_id"`
	QualityProfileID      sql.NullInt64  `json:"quality_profile_id"`
	Monitored             int64          `json:"monitored"`
	Status                string         `json:"status"`
	ActiveDownloadID      sql.NullString `json:"active_download_id"`
	StatusMessage         sql.NullString `json:"status_message"`
	ReleaseDate           sql.NullTime   `json:"release_date"`
	PhysicalReleaseDate   sql.NullTime   `json:"physical_release_date"`
	AddedAt               sql.NullTime   `json:"added_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	TheatricalReleaseDate sql.NullTime   `json:"theatrical_release_date"`
	Studio                sql.NullString `json:"studio"`
	TvdbID                sql.NullInt64  `json:"tvdb_id"`
	ContentRating         sql.NullString `json:"content_rating"`
	AddedBy               sql.NullInt64  `json:"added_by"`
}

type MovieFile struct {
	ID               int64          `json:"id"`
	MovieID          int64          `json:"movie_id"`
	Path             string         `json:"path"`
	Size             int64          `json:"size"`
	Quality          sql.NullString `json:"quality"`
	VideoCodec       sql.NullString `json:"video_codec"`
	AudioCodec       sql.NullString `json:"audio_codec"`
	Resolution       sql.NullString `json:"resolution"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	QualityID        sql.NullInt64  `json:"quality_id"`
	OriginalPath     sql.NullString `json:"original_path"`
	OriginalFilename sql.NullString `json:"original_filename"`
	ImportedAt       sql.NullTime   `json:"imported_at"`
	SlotID           sql.NullInt64  `json:"slot_id"`
	AudioChannels    sql.NullString `json:"audio_channels"`
	DynamicRange     sql.NullString `json:"dynamic_range"`
}

type MovieSlotAssignment struct {
	ID               int64          `json:"id"`
	MovieID          int64          `json:"movie_id"`
	SlotID           int64          `json:"slot_id"`
	FileID           sql.NullInt64  `json:"file_id"`
	Monitored        int64          `json:"monitored"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	Status           string         `json:"status"`
	ActiveDownloadID sql.NullString `json:"active_download_id"`
	StatusMessage    sql.NullString `json:"status_message"`
}

type MultiVersionSetting struct {
	ID              int64        `json:"id"`
	Enabled         int64        `json:"enabled"`
	DryRunCompleted int64        `json:"dry_run_completed"`
	LastMigrationAt sql.NullTime `json:"last_migration_at"`
	CreatedAt       sql.NullTime `json:"created_at"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type NetworkLogo struct {
	Name      string       `json:"name"`
	LogoUrl   string       `json:"logo_url"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Notification struct {
	ID                    int64     `json:"id"`
	Name                  string    `json:"name"`
	Type                  string    `json:"type"`
	Enabled               int64     `json:"enabled"`
	Settings              string    `json:"settings"`
	OnGrab                int64     `json:"on_grab"`
	OnImport              int64     `json:"on_import"`
	OnUpgrade             int64     `json:"on_upgrade"`
	OnMovieAdded          int64     `json:"on_movie_added"`
	OnMovieDeleted        int64     `json:"on_movie_deleted"`
	OnSeriesAdded         int64     `json:"on_series_added"`
	OnSeriesDeleted       int64     `json:"on_series_deleted"`
	OnHealthIssue         int64     `json:"on_health_issue"`
	OnHealthRestored      int64     `json:"on_health_restored"`
	OnAppUpdate           int64     `json:"on_app_update"`
	IncludeHealthWarnings int64     `json:"include_health_warnings"`
	Tags                  string    `json:"tags"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type NotificationStatus struct {
	NotificationID    int64        `json:"notification_id"`
	InitialFailure    sql.NullTime `json:"initial_failure"`
	MostRecentFailure sql.NullTime `json:"most_recent_failure"`
	EscalationLevel   int64        `json:"escalation_level"`
	DisabledTill      sql.NullTime `json:"disabled_till"`
}

type PasskeyCredential struct {
	ID                  string         `json:"id"`
	UserID              int64          `json:"user_id"`
	CredentialID        []byte         `json:"credential_id"`
	PublicKey           []byte         `json:"public_key"`
	AttestationType     string         `json:"attestation_type"`
	Transport           sql.NullString `json:"transport"`
	FlagsUserPresent    bool           `json:"flags_user_present"`
	FlagsUserVerified   bool           `json:"flags_user_verified"`
	FlagsBackupEligible bool           `json:"flags_backup_eligible"`
	FlagsBackupState    bool           `json:"flags_backup_state"`
	SignCount           int64          `json:"sign_count"`
	Name                string         `json:"name"`
	CreatedAt           time.Time      `json:"created_at"`
	LastUsedAt          sql.NullTime   `json:"last_used_at"`
}

type PlexRefreshQueue struct {
	ID             int64          `json:"id"`
	NotificationID int64          `json:"notification_id"`
	ServerID       string         `json:"server_id"`
	SectionKey     int64          `json:"section_key"`
	Path           sql.NullString `json:"path"`
	QueuedAt       time.Time      `json:"queued_at"`
}

type PortalInvitation struct {
	ID               int64         `json:"id"`
	Username         string        `json:"username"`
	Token            string        `json:"token"`
	ExpiresAt        time.Time     `json:"expires_at"`
	UsedAt           sql.NullTime  `json:"used_at"`
	CreatedAt        time.Time     `json:"created_at"`
	QualityProfileID sql.NullInt64 `json:"quality_profile_id"`
	AutoApprove      int64         `json:"auto_approve"`
}

type PortalNotification struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	RequestID sql.NullInt64 `json:"request_id"`
	Type      string        `json:"type"`
	Title     string        `json:"title"`
	Message   string        `json:"message"`
	Read      int64         `json:"read"`
	CreatedAt time.Time     `json:"created_at"`
}

type PortalUser struct {
	ID               int64          `json:"id"`
	Username         string         `json:"username"`
	PasswordHash     string         `json:"password_hash"`
	DisplayName      sql.NullString `json:"display_name"`
	QualityProfileID sql.NullInt64  `json:"quality_profile_id"`
	AutoApprove      int64          `json:"auto_approve"`
	Enabled          int64          `json:"enabled"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	IsAdmin          int64          `json:"is_admin"`
}

type ProwlarrConfig struct {
	ID                    int64          `json:"id"`
	Enabled               int64          `json:"enabled"`
	Url                   string         `json:"url"`
	ApiKey                string         `json:"api_key"`
	MovieCategories       string         `json:"movie_categories"`
	TvCategories          string         `json:"tv_categories"`
	Timeout               int64          `json:"timeout"`
	SkipSslVerify         int64          `json:"skip_ssl_verify"`
	Capabilities          sql.NullString `json:"capabilities"`
	CapabilitiesUpdatedAt sql.NullTime   `json:"capabilities_updated_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type ProwlarrIndexerSetting struct {
	ProwlarrIndexerID int64          `json:"prowlarr_indexer_id"`
	Priority          int64          `json:"priority"`
	ContentType       string         `json:"content_type"`
	MovieCategories   sql.NullString `json:"movie_categories"`
	TvCategories      sql.NullString `json:"tv_categories"`
	SuccessCount      int64          `json:"success_count"`
	FailureCount      int64          `json:"failure_count"`
	LastFailureAt     sql.NullTime   `json:"last_failure_at"`
	LastFailureReason sql.NullString `json:"last_failure_reason"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type QualityProfile struct {
	ID                      int64        `json:"id"`
	Name                    string       `json:"name"`
	Cutoff                  int64        `json:"cutoff"`
	Items                   string       `json:"items"`
	CreatedAt               sql.NullTime `json:"created_at"`
	UpdatedAt               sql.NullTime `json:"updated_at"`
	HdrSettings             string       `json:"hdr_settings"`
	VideoCodecSettings      string       `json:"video_codec_settings"`
	AudioCodecSettings      string       `json:"audio_codec_settings"`
	AudioChannelSettings    string       `json:"audio_channel_settings"`
	UpgradesEnabled         int64        `json:"upgrades_enabled"`
	AllowAutoApprove        int64        `json:"allow_auto_approve"`
	UpgradeStrategy         string       `json:"upgrade_strategy"`
	CutoffOverridesStrategy int64        `json:"cutoff_overrides_strategy"`
}

type QueueMedium struct {
	ID                int64          `json:"id"`
	DownloadMappingID int64          `json:"download_mapping_id"`
	EpisodeID         sql.NullInt64  `json:"episode_id"`
	MovieID           sql.NullInt64  `json:"movie_id"`
	FilePath          sql.NullString `json:"file_path"`
	FileStatus        string         `json:"file_status"`
	ErrorMessage      sql.NullString `json:"error_message"`
	ImportAttempts    int64          `json:"import_attempts"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	TargetSlotID      sql.NullInt64  `json:"target_slot_id"`
}

type Request struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	MediaType        string         `json:"media_type"`
	TmdbID           sql.NullInt64  `json:"tmdb_id"`
	TvdbID           sql.NullInt64  `json:"tvdb_id"`
	Title            string         `json:"title"`
	Year             sql.NullInt64  `json:"year"`
	SeasonNumber     sql.NullInt64  `json:"season_number"`
	EpisodeNumber    sql.NullInt64  `json:"episode_number"`
	Status           string         `json:"status"`
	MonitorType      sql.NullString `json:"monitor_type"`
	DeniedReason     sql.NullString `json:"denied_reason"`
	ApprovedAt       sql.NullTime   `json:"approved_at"`
	ApprovedBy       sql.NullInt64  `json:"approved_by"`
	MediaID          sql.NullInt64  `json:"media_id"`
	TargetSlotID     sql.NullInt64  `json:"target_slot_id"`
	PosterUrl        sql.NullString `json:"poster_url"`
	RequestedSeasons sql.NullString `json:"requested_seasons"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type RequestWatcher struct {
	RequestID int64     `json:"request_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RootFolder struct {
	ID        int64         `json:"id"`
	Path      string        `json:"path"`
	Name      string        `json:"name"`
	MediaType string        `json:"media_type"`
	FreeSpace sql.NullInt64 `json:"free_space"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Season struct {
	ID           int64          `json:"id"`
	SeriesID     int64          `json:"series_id"`
	SeasonNumber int64          `json:"season_number"`
	Monitored    int64          `json:"monitored"`
	Overview     sql.NullString `json:"overview"`
	PosterUrl    sql.NullString `json:"poster_url"`
}

type Series struct {
	ID               int64          `json:"id"`
	Title            string         `json:"title"`
	SortTitle        string         `json:"sort_title"`
	Year             sql.NullInt64  `json:"year"`
	TvdbID           sql.NullInt64  `json:"tvdb_id"`
	TmdbID           sql.NullInt64  `json:"tmdb_id"`
	ImdbID           sql.NullString `json:"imdb_id"`
	Overview         sql.NullString `json:"overview"`
	Runtime          sql.NullInt64  `json:"runtime"`
	Path             sql.NullString `json:"path"`
	RootFolderID     sql.NullInt64  `json:"root_folder_id"`
	QualityProfileID sql.NullInt64  `json:"quality_profile_id"`
	Monitored        int64          `json:"monitored"`
	SeasonFolder     int64          `json:"season_folder"`
	ProductionStatus string         `json:"production_status"`
	Network          sql.NullString `json:"network"`
	FormatType       sql.NullString `json:"format_type"`
	AddedAt          sql.NullTime   `json:"added_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	NetworkLogoUrl   sql.NullString `json:"network_logo_url"`
	AddedBy          sql.NullInt64  `json:"added_by"`
}

type Setting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type UserNotification struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Type        string    `json:"type"`
	Name        string    `json:"name"`
	Settings    string    `json:"settings"`
	OnAvailable int64     `json:"on_available"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	OnApproved  int64     `json:"on_approved"`
	OnDenied    int64     `json:"on_denied"`
}

type UserQuota struct {
	UserID        int64         `json:"user_id"`
	MoviesLimit   sql.NullInt64 `json:"movies_limit"`
	SeasonsLimit  sql.NullInt64 `json:"seasons_limit"`
	EpisodesLimit sql.NullInt64 `json:"episodes_limit"`
	MoviesUsed    int64         `json:"movies_used"`
	SeasonsUsed   int64         `json:"seasons_used"`
	EpisodesUsed  int64         `json:"episodes_used"`
	PeriodStart   time.Time     `json:"period_start"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type VersionSlot struct {
	ID                int64         `json:"id"`
	SlotNumber        int64         `json:"slot_number"`
	Name              string        `json:"name"`
	Enabled           int64         `json:"enabled"`
	QualityProfileID  sql.NullInt64 `json:"quality_profile_id"`
	DisplayOrder      int64         `json:"display_order"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
	MovieRootFolderID sql.NullInt64 `json:"movie_root_folder_id"`
	TvRootFolderID    sql.NullInt64 `json:"tv_root_folder_id"`
}
