// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: module_naming_settings.sql

package sqlc

import (
	"context"
)

const deleteModuleNamingSettings = `-- name: DeleteModuleNamingSettings :exec
DELETE FROM module_naming_settings WHERE module_type = ?
`

func (q *Queries) DeleteModuleNamingSettings(ctx context.Context, moduleType string) error {
	_, err := q.db.ExecContext(ctx, deleteModuleNamingSettings, moduleType)
	return err
}

const getModuleNamingSetting = `-- name: GetModuleNamingSetting :one
SELECT setting_value
FROM module_naming_settings
WHERE module_type = ? AND setting_key = ?
`

type GetModuleNamingSettingParams struct {
	ModuleType string `json:"module_type"`
	SettingKey string `json:"setting_key"`
}

func (q *Queries) GetModuleNamingSetting(ctx context.Context, arg GetModuleNamingSettingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getModuleNamingSetting, arg.ModuleType, arg.SettingKey)
	var setting_value string
	err := row.Scan(&setting_value)
	return setting_value, err
}

const listModuleNamingSettings = `-- name: ListModuleNamingSettings :many
SELECT setting_key, setting_value
FROM module_naming_settings
WHERE module_type = ?
`

type ListModuleNamingSettingsRow struct {
	SettingKey   string `json:"setting_key"`
	SettingValue string `json:"setting_value"`
}

func (q *Queries) ListModuleNamingSettings(ctx context.Context, moduleType string) ([]*ListModuleNamingSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listModuleNamingSettings, moduleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListModuleNamingSettingsRow{}
	for rows.Next() {
		var i ListModuleNamingSettingsRow
		if err := rows.Scan(&i.SettingKey, &i.SettingValue); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModuleNamingSetting = `-- name: UpsertModuleNamingSetting :exec
INSERT INTO module_naming_settings (module_type, setting_key, setting_value)
VALUES (?, ?, ?)
ON CONFLICT(module_type, setting_key) DO UPDATE SET setting_value = excluded.setting_value
`

type UpsertModuleNamingSettingParams struct {
	ModuleType   string `json:"module_type"`
	SettingKey   string `json:"setting_key"`
	SettingValue string `json:"setting_value"`
}

func (q *Queries) UpsertModuleNamingSetting(ctx context.Context, arg UpsertModuleNamingSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertModuleNamingSetting, arg.ModuleType, arg.SettingKey, arg.SettingValue)
	return err
}
