// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_logos.sql

package sqlc

import (
	"context"
)

const getAllNetworkLogos = `-- name: GetAllNetworkLogos :many
SELECT name, logo_url, updated_at FROM network_logos ORDER BY name
`

func (q *Queries) GetAllNetworkLogos(ctx context.Context) ([]*NetworkLogo, error) {
	rows, err := q.db.QueryContext(ctx, getAllNetworkLogos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*NetworkLogo{}
	for rows.Next() {
		var i NetworkLogo
		if err := rows.Scan(&i.Name, &i.LogoUrl, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetworkLogo = `-- name: GetNetworkLogo :one
SELECT name, logo_url, updated_at FROM network_logos WHERE name = ? LIMIT 1
`

func (q *Queries) GetNetworkLogo(ctx context.Context, name string) (*NetworkLogo, error) {
	row := q.db.QueryRowContext(ctx, getNetworkLogo, name)
	var i NetworkLogo
	err := row.Scan(&i.Name, &i.LogoUrl, &i.UpdatedAt)
	return &i, err
}

const upsertNetworkLogo = `-- name: UpsertNetworkLogo :exec
INSERT INTO network_logos (name, logo_url, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(name) DO UPDATE SET
    logo_url = excluded.logo_url,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertNetworkLogoParams struct {
	Name    string `json:"name"`
	LogoUrl string `json:"logo_url"`
}

func (q *Queries) UpsertNetworkLogo(ctx context.Context, arg UpsertNetworkLogoParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetworkLogo, arg.Name, arg.LogoUrl)
	return err
}
