// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const clearNotificationStatus = `-- name: ClearNotificationStatus :exec
DELETE FROM notification_status WHERE notification_id = ?
`

func (q *Queries) ClearNotificationStatus(ctx context.Context, notificationID int64) error {
	_, err := q.db.ExecContext(ctx, clearNotificationStatus, notificationID)
	return err
}

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications
`

func (q *Queries) CountNotifications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotifications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    name, type, enabled, settings,
    on_grab, on_import, on_upgrade,
    on_movie_added, on_movie_deleted,
    on_series_added, on_series_deleted,
    on_health_issue, on_health_restored, on_app_update,
    include_health_warnings, tags
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, enabled, settings, on_grab, on_import, on_upgrade, on_movie_added, on_movie_deleted, on_series_added, on_series_deleted, on_health_issue, on_health_restored, on_app_update, include_health_warnings, tags, created_at, updated_at
`

type CreateNotificationParams struct {
	Name                  string `json:"name"`
	Type                  string `json:"type"`
	Enabled               int64  `json:"enabled"`
	Settings              string `json:"settings"`
	OnGrab                int64  `json:"on_grab"`
	OnImport              int64  `json:"on_import"`
	OnUpgrade             int64  `json:"on_upgrade"`
	OnMovieAdded          int64  `json:"on_movie_added"`
	OnMovieDeleted        int64  `json:"on_movie_deleted"`
	OnSeriesAdded         int64  `json:"on_series_added"`
	OnSeriesDeleted       int64  `json:"on_series_deleted"`
	OnHealthIssue         int64  `json:"on_health_issue"`
	OnHealthRestored      int64  `json:"on_health_restored"`
	OnAppUpdate           int64  `json:"on_app_update"`
	IncludeHealthWarnings int64  `json:"include_health_warnings"`
	Tags                  string `json:"tags"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Settings,
		arg.OnGrab,
		arg.OnImport,
		arg.OnUpgrade,
		arg.OnMovieAdded,
		arg.OnMovieDeleted,
		arg.OnSeriesAdded,
		arg.OnSeriesDeleted,
		arg.OnHealthIssue,
		arg.OnHealthRestored,
		arg.OnAppUpdate,
		arg.IncludeHealthWarnings,
		arg.Tags,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Settings,
		&i.OnGrab,
		&i.OnImport,
		&i.OnUpgrade,
		&i.OnMovieAdded,
		&i.OnMovieDeleted,
		&i.OnSeriesAdded,
		&i.OnSeriesDeleted,
		&i.OnHealthIssue,
		&i.OnHealthRestored,
		&i.OnAppUpdate,
		&i.IncludeHealthWarnings,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = ?
`

func (q *Queries) DeleteNotification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, name, type, enabled, settings, on_grab, on_import, on_upgrade, on_movie_added, on_movie_deleted, on_series_added, on_series_deleted, on_health_issue, on_health_restored, on_app_update, include_health_warnings, tags, created_at, updated_at FROM notifications WHERE id = ? LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id int64) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Settings,
		&i.OnGrab,
		&i.OnImport,
		&i.OnUpgrade,
		&i.OnMovieAdded,
		&i.OnMovieDeleted,
		&i.OnSeriesAdded,
		&i.OnSeriesDeleted,
		&i.OnHealthIssue,
		&i.OnHealthRestored,
		&i.OnAppUpdate,
		&i.IncludeHealthWarnings,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getNotificationStatus = `-- name: GetNotificationStatus :one

SELECT notification_id, initial_failure, most_recent_failure, escalation_level, disabled_till FROM notification_status WHERE notification_id = ? LIMIT 1
`

// Notification status queries for failure tracking
func (q *Queries) GetNotificationStatus(ctx context.Context, notificationID int64) (*NotificationStatus, error) {
	row := q.db.QueryRowContext(ctx, getNotificationStatus, notificationID)
	var i NotificationStatus
	err := row.Scan(
		&i.NotificationID,
		&i.InitialFailure,
		&i.MostRecentFailure,
		&i.EscalationLevel,
		&i.DisabledTill,
	)
	return &i, err
}

const listDisabledNotifications = `-- name: ListDisabledNotifications :many
SELECT n.id, n.name, n.type, n.enabled, n.settings, n.on_grab, n.on_import, n.on_upgrade, n.on_movie_added, n.on_movie_deleted, n.on_series_added, n.on_series_deleted, n.on_health_issue, n.on_health_restored, n.on_app_update, n.include_health_warnings, n.tags, n.created_at, n.updated_at, ns.disabled_till
FROM notifications n
JOIN notification_status ns ON n.id = ns.notification_id
WHERE ns.disabled_till IS NOT NULL AND ns.disabled_till > CURRENT_TIMESTAMP
`

type ListDisabledNotificationsRow struct {
	ID                    int64        `json:"id"`
	Name                  string       `json:"name"`
	Type                  string       `json:"type"`
	Enabled               int64        `json:"enabled"`
	Settings              string       `json:"settings"`
	OnGrab                int64        `json:"on_grab"`
	OnImport              int64        `json:"on_import"`
	OnUpgrade             int64        `json:"on_upgrade"`
	OnMovieAdded          int64        `json:"on_movie_added"`
	OnMovieDeleted        int64        `json:"on_movie_deleted"`
	OnSeriesAdded         int64        `json:"on_series_added"`
	OnSeriesDeleted       int64        `json:"on_series_deleted"`
	OnHealthIssue         int64        `json:"on_health_issue"`
	OnHealthRestored      int64        `json:"on_health_restored"`
	OnAppUpdate           int64        `json:"on_app_update"`
	IncludeHealthWarnings int64        `json:"include_health_warnings"`
	Tags                  string       `json:"tags"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
	DisabledTill          sql.NullTime `json:"disabled_till"`
}

func (q *Queries) ListDisabledNotifications(ctx context.Context) ([]*ListDisabledNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDisabledNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListDisabledNotificationsRow{}
	for rows.Next() {
		var i ListDisabledNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Settings,
			&i.OnGrab,
			&i.OnImport,
			&i.OnUpgrade,
			&i.OnMovieAdded,
			&i.OnMovieDeleted,
			&i.OnSeriesAdded,
			&i.OnSeriesDeleted,
			&i.OnHealthIssue,
			&i.OnHealthRestored,
			&i.OnAppUpdate,
			&i.IncludeHealthWarnings,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledTill,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledNotifications = `-- name: ListEnabledNotifications :many
SELECT id, name, type, enabled, settings, on_grab, on_import, on_upgrade, on_movie_added, on_movie_deleted, on_series_added, on_series_deleted, on_health_issue, on_health_restored, on_app_update, include_health_warnings, tags, created_at, updated_at FROM notifications WHERE enabled = 1 ORDER BY name
`

func (q *Queries) ListEnabledNotifications(ctx context.Context) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Settings,
			&i.OnGrab,
			&i.OnImport,
			&i.OnUpgrade,
			&i.OnMovieAdded,
			&i.OnMovieDeleted,
			&i.OnSeriesAdded,
			&i.OnSeriesDeleted,
			&i.OnHealthIssue,
			&i.OnHealthRestored,
			&i.OnAppUpdate,
			&i.IncludeHealthWarnings,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, name, type, enabled, settings, on_grab, on_import, on_upgrade, on_movie_added, on_movie_deleted, on_series_added, on_series_deleted, on_health_issue, on_health_restored, on_app_update, include_health_warnings, tags, created_at, updated_at FROM notifications ORDER BY name
`

func (q *Queries) ListNotifications(ctx context.Context) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Settings,
			&i.OnGrab,
			&i.OnImport,
			&i.OnUpgrade,
			&i.OnMovieAdded,
			&i.OnMovieDeleted,
			&i.OnSeriesAdded,
			&i.OnSeriesDeleted,
			&i.OnHealthIssue,
			&i.OnHealthRestored,
			&i.OnAppUpdate,
			&i.IncludeHealthWarnings,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForEvent = `-- name: ListNotificationsForEvent :many
SELECT id, name, type, enabled, settings, on_grab, on_import, on_upgrade, on_movie_added, on_movie_deleted, on_series_added, on_series_deleted, on_health_issue, on_health_restored, on_app_update, include_health_warnings, tags, created_at, updated_at FROM notifications
WHERE enabled = 1
ORDER BY name
`

// Returns notifications enabled for a specific event type
// Event type is passed as parameter, we check all event columns
func (q *Queries) ListNotificationsForEvent(ctx context.Context) ([]*Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForEvent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Settings,
			&i.OnGrab,
			&i.OnImport,
			&i.OnUpgrade,
			&i.OnMovieAdded,
			&i.OnMovieDeleted,
			&i.OnSeriesAdded,
			&i.OnSeriesDeleted,
			&i.OnHealthIssue,
			&i.OnHealthRestored,
			&i.OnAppUpdate,
			&i.IncludeHealthWarnings,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotification = `-- name: UpdateNotification :one
UPDATE notifications SET
    name = ?,
    type = ?,
    enabled = ?,
    settings = ?,
    on_grab = ?,
    on_import = ?,
    on_upgrade = ?,
    on_movie_added = ?,
    on_movie_deleted = ?,
    on_series_added = ?,
    on_series_deleted = ?,
    on_health_issue = ?,
    on_health_restored = ?,
    on_app_update = ?,
    include_health_warnings = ?,
    tags = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, enabled, settings, on_grab, on_import, on_upgrade, on_movie_added, on_movie_deleted, on_series_added, on_series_deleted, on_health_issue, on_health_restored, on_app_update, include_health_warnings, tags, created_at, updated_at
`

type UpdateNotificationParams struct {
	Name                  string `json:"name"`
	Type                  string `json:"type"`
	Enabled               int64  `json:"enabled"`
	Settings              string `json:"settings"`
	OnGrab                int64  `json:"on_grab"`
	OnImport              int64  `json:"on_import"`
	OnUpgrade             int64  `json:"on_upgrade"`
	OnMovieAdded          int64  `json:"on_movie_added"`
	OnMovieDeleted        int64  `json:"on_movie_deleted"`
	OnSeriesAdded         int64  `json:"on_series_added"`
	OnSeriesDeleted       int64  `json:"on_series_deleted"`
	OnHealthIssue         int64  `json:"on_health_issue"`
	OnHealthRestored      int64  `json:"on_health_restored"`
	OnAppUpdate           int64  `json:"on_app_update"`
	IncludeHealthWarnings int64  `json:"include_health_warnings"`
	Tags                  string `json:"tags"`
	ID                    int64  `json:"id"`
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (*Notification, error) {
	row := q.db.QueryRowContext(ctx, updateNotification,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.Settings,
		arg.OnGrab,
		arg.OnImport,
		arg.OnUpgrade,
		arg.OnMovieAdded,
		arg.OnMovieDeleted,
		arg.OnSeriesAdded,
		arg.OnSeriesDeleted,
		arg.OnHealthIssue,
		arg.OnHealthRestored,
		arg.OnAppUpdate,
		arg.IncludeHealthWarnings,
		arg.Tags,
		arg.ID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Settings,
		&i.OnGrab,
		&i.OnImport,
		&i.OnUpgrade,
		&i.OnMovieAdded,
		&i.OnMovieDeleted,
		&i.OnSeriesAdded,
		&i.OnSeriesDeleted,
		&i.OnHealthIssue,
		&i.OnHealthRestored,
		&i.OnAppUpdate,
		&i.IncludeHealthWarnings,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertNotificationStatus = `-- name: UpsertNotificationStatus :exec
INSERT INTO notification_status (notification_id, initial_failure, most_recent_failure, escalation_level, disabled_till)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(notification_id) DO UPDATE SET
    initial_failure = COALESCE(excluded.initial_failure, notification_status.initial_failure),
    most_recent_failure = excluded.most_recent_failure,
    escalation_level = excluded.escalation_level,
    disabled_till = excluded.disabled_till
`

type UpsertNotificationStatusParams struct {
	NotificationID    int64        `json:"notification_id"`
	InitialFailure    sql.NullTime `json:"initial_failure"`
	MostRecentFailure sql.NullTime `json:"most_recent_failure"`
	EscalationLevel   int64        `json:"escalation_level"`
	DisabledTill      sql.NullTime `json:"disabled_till"`
}

func (q *Queries) UpsertNotificationStatus(ctx context.Context, arg UpsertNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationStatus,
		arg.NotificationID,
		arg.InitialFailure,
		arg.MostRecentFailure,
		arg.EscalationLevel,
		arg.DisabledTill,
	)
	return err
}
