// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_invitations.sql

package sqlc

import (
	"context"
	"time"
)

const countPendingPortalInvitations = `-- name: CountPendingPortalInvitations :one
SELECT COUNT(*) FROM portal_invitations WHERE used_at IS NULL
`

func (q *Queries) CountPendingPortalInvitations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingPortalInvitations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPortalInvitation = `-- name: CreatePortalInvitation :one
INSERT INTO portal_invitations (username, token, expires_at)
VALUES (?, ?, ?)
RETURNING id, username, token, expires_at, used_at, created_at
`

type CreatePortalInvitationParams struct {
	Username  string    `json:"username"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePortalInvitation(ctx context.Context, arg CreatePortalInvitationParams) (*PortalInvitation, error) {
	row := q.db.QueryRowContext(ctx, createPortalInvitation, arg.Username, arg.Token, arg.ExpiresAt)
	var i PortalInvitation
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredPortalInvitations = `-- name: DeleteExpiredPortalInvitations :exec
DELETE FROM portal_invitations
WHERE expires_at < CURRENT_TIMESTAMP AND used_at IS NULL
`

func (q *Queries) DeleteExpiredPortalInvitations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPortalInvitations)
	return err
}

const deletePortalInvitation = `-- name: DeletePortalInvitation :exec
DELETE FROM portal_invitations WHERE id = ?
`

func (q *Queries) DeletePortalInvitation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePortalInvitation, id)
	return err
}

const getPortalInvitation = `-- name: GetPortalInvitation :one
SELECT id, username, token, expires_at, used_at, created_at FROM portal_invitations WHERE id = ? LIMIT 1
`

func (q *Queries) GetPortalInvitation(ctx context.Context, id int64) (*PortalInvitation, error) {
	row := q.db.QueryRowContext(ctx, getPortalInvitation, id)
	var i PortalInvitation
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getPortalInvitationByToken = `-- name: GetPortalInvitationByToken :one
SELECT id, username, token, expires_at, used_at, created_at FROM portal_invitations WHERE token = ? LIMIT 1
`

func (q *Queries) GetPortalInvitationByToken(ctx context.Context, token string) (*PortalInvitation, error) {
	row := q.db.QueryRowContext(ctx, getPortalInvitationByToken, token)
	var i PortalInvitation
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getPortalInvitationByUsername = `-- name: GetPortalInvitationByUsername :one
SELECT id, username, token, expires_at, used_at, created_at FROM portal_invitations WHERE username = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPortalInvitationByUsername(ctx context.Context, username string) (*PortalInvitation, error) {
	row := q.db.QueryRowContext(ctx, getPortalInvitationByUsername, username)
	var i PortalInvitation
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const listPendingPortalInvitations = `-- name: ListPendingPortalInvitations :many
SELECT id, username, token, expires_at, used_at, created_at FROM portal_invitations
WHERE used_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPendingPortalInvitations(ctx context.Context) ([]*PortalInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPortalInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PortalInvitation{}
	for rows.Next() {
		var i PortalInvitation
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Token,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortalInvitations = `-- name: ListPortalInvitations :many
SELECT id, username, token, expires_at, used_at, created_at FROM portal_invitations ORDER BY created_at DESC
`

func (q *Queries) ListPortalInvitations(ctx context.Context) ([]*PortalInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listPortalInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PortalInvitation{}
	for rows.Next() {
		var i PortalInvitation
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Token,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPortalInvitationUsed = `-- name: MarkPortalInvitationUsed :exec
UPDATE portal_invitations SET used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) MarkPortalInvitationUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPortalInvitationUsed, id)
	return err
}

const updatePortalInvitationToken = `-- name: UpdatePortalInvitationToken :one
UPDATE portal_invitations SET
    token = ?,
    expires_at = ?,
    used_at = NULL
WHERE id = ?
RETURNING id, username, token, expires_at, used_at, created_at
`

type UpdatePortalInvitationTokenParams struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	ID        int64     `json:"id"`
}

func (q *Queries) UpdatePortalInvitationToken(ctx context.Context, arg UpdatePortalInvitationTokenParams) (*PortalInvitation, error) {
	row := q.db.QueryRowContext(ctx, updatePortalInvitationToken, arg.Token, arg.ExpiresAt, arg.ID)
	var i PortalInvitation
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}
