// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_notifications.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUnreadPortalNotifications = `-- name: CountUnreadPortalNotifications :one
SELECT COUNT(*) FROM portal_notifications
WHERE user_id = ? AND read = 0
`

func (q *Queries) CountUnreadPortalNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadPortalNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPortalNotification = `-- name: CreatePortalNotification :one
INSERT INTO portal_notifications (
    user_id, request_id, type, title, message
) VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, request_id, type, title, message, read, created_at
`

type CreatePortalNotificationParams struct {
	UserID    int64         `json:"user_id"`
	RequestID sql.NullInt64 `json:"request_id"`
	Type      string        `json:"type"`
	Title     string        `json:"title"`
	Message   string        `json:"message"`
}

func (q *Queries) CreatePortalNotification(ctx context.Context, arg CreatePortalNotificationParams) (*PortalNotification, error) {
	row := q.db.QueryRowContext(ctx, createPortalNotification,
		arg.UserID,
		arg.RequestID,
		arg.Type,
		arg.Title,
		arg.Message,
	)
	var i PortalNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteOldPortalNotifications = `-- name: DeleteOldPortalNotifications :exec
DELETE FROM portal_notifications
WHERE user_id = ? AND created_at < ?
`

type DeleteOldPortalNotificationsParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) DeleteOldPortalNotifications(ctx context.Context, arg DeleteOldPortalNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldPortalNotifications, arg.UserID, arg.CreatedAt)
	return err
}

const deletePortalNotification = `-- name: DeletePortalNotification :exec
DELETE FROM portal_notifications WHERE id = ? AND user_id = ?
`

type DeletePortalNotificationParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePortalNotification(ctx context.Context, arg DeletePortalNotificationParams) error {
	_, err := q.db.ExecContext(ctx, deletePortalNotification, arg.ID, arg.UserID)
	return err
}

const listPortalNotifications = `-- name: ListPortalNotifications :many
SELECT id, user_id, request_id, type, title, message, read, created_at FROM portal_notifications
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPortalNotificationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPortalNotifications(ctx context.Context, arg ListPortalNotificationsParams) ([]*PortalNotification, error) {
	rows, err := q.db.QueryContext(ctx, listPortalNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PortalNotification{}
	for rows.Next() {
		var i PortalNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadPortalNotifications = `-- name: ListUnreadPortalNotifications :many
SELECT id, user_id, request_id, type, title, message, read, created_at FROM portal_notifications
WHERE user_id = ? AND read = 0
ORDER BY created_at DESC
`

func (q *Queries) ListUnreadPortalNotifications(ctx context.Context, userID int64) ([]*PortalNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUnreadPortalNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PortalNotification{}
	for rows.Next() {
		var i PortalNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllPortalNotificationsRead = `-- name: MarkAllPortalNotificationsRead :exec
UPDATE portal_notifications SET read = 1
WHERE user_id = ? AND read = 0
`

func (q *Queries) MarkAllPortalNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, markAllPortalNotificationsRead, userID)
	return err
}

const markPortalNotificationRead = `-- name: MarkPortalNotificationRead :exec
UPDATE portal_notifications SET read = 1
WHERE id = ? AND user_id = ?
`

type MarkPortalNotificationReadParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkPortalNotificationRead(ctx context.Context, arg MarkPortalNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markPortalNotificationRead, arg.ID, arg.UserID)
	return err
}
