// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prowlarr_config.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearProwlarrConfigCapabilities = `-- name: ClearProwlarrConfigCapabilities :exec
UPDATE prowlarr_config SET
    capabilities = NULL,
    capabilities_updated_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

func (q *Queries) ClearProwlarrConfigCapabilities(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearProwlarrConfigCapabilities)
	return err
}

const getProwlarrConfig = `-- name: GetProwlarrConfig :one
SELECT id, enabled, url, api_key, movie_categories, tv_categories, timeout, skip_ssl_verify, capabilities, capabilities_updated_at, created_at, updated_at FROM prowlarr_config WHERE id = 1 LIMIT 1
`

func (q *Queries) GetProwlarrConfig(ctx context.Context) (*ProwlarrConfig, error) {
	row := q.db.QueryRowContext(ctx, getProwlarrConfig)
	var i ProwlarrConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Url,
		&i.ApiKey,
		&i.MovieCategories,
		&i.TvCategories,
		&i.Timeout,
		&i.SkipSslVerify,
		&i.Capabilities,
		&i.CapabilitiesUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const isProwlarrEnabled = `-- name: IsProwlarrEnabled :one
SELECT enabled FROM prowlarr_config WHERE id = 1 LIMIT 1
`

func (q *Queries) IsProwlarrEnabled(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, isProwlarrEnabled)
	var enabled int64
	err := row.Scan(&enabled)
	return enabled, err
}

const setProwlarrEnabled = `-- name: SetProwlarrEnabled :exec
UPDATE prowlarr_config SET
    enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

func (q *Queries) SetProwlarrEnabled(ctx context.Context, enabled int64) error {
	_, err := q.db.ExecContext(ctx, setProwlarrEnabled, enabled)
	return err
}

const updateProwlarrConfig = `-- name: UpdateProwlarrConfig :one
UPDATE prowlarr_config SET
    enabled = ?,
    url = ?,
    api_key = ?,
    movie_categories = ?,
    tv_categories = ?,
    timeout = ?,
    skip_ssl_verify = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, enabled, url, api_key, movie_categories, tv_categories, timeout, skip_ssl_verify, capabilities, capabilities_updated_at, created_at, updated_at
`

type UpdateProwlarrConfigParams struct {
	Enabled         int64  `json:"enabled"`
	Url             string `json:"url"`
	ApiKey          string `json:"api_key"`
	MovieCategories string `json:"movie_categories"`
	TvCategories    string `json:"tv_categories"`
	Timeout         int64  `json:"timeout"`
	SkipSslVerify   int64  `json:"skip_ssl_verify"`
}

func (q *Queries) UpdateProwlarrConfig(ctx context.Context, arg UpdateProwlarrConfigParams) (*ProwlarrConfig, error) {
	row := q.db.QueryRowContext(ctx, updateProwlarrConfig,
		arg.Enabled,
		arg.Url,
		arg.ApiKey,
		arg.MovieCategories,
		arg.TvCategories,
		arg.Timeout,
		arg.SkipSslVerify,
	)
	var i ProwlarrConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Url,
		&i.ApiKey,
		&i.MovieCategories,
		&i.TvCategories,
		&i.Timeout,
		&i.SkipSslVerify,
		&i.Capabilities,
		&i.CapabilitiesUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateProwlarrConfigCapabilities = `-- name: UpdateProwlarrConfigCapabilities :exec
UPDATE prowlarr_config SET
    capabilities = ?,
    capabilities_updated_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

func (q *Queries) UpdateProwlarrConfigCapabilities(ctx context.Context, capabilities sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateProwlarrConfigCapabilities, capabilities)
	return err
}
