// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prowlarr_indexer_settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAllProwlarrIndexerSettings = `-- name: DeleteAllProwlarrIndexerSettings :exec
DELETE FROM prowlarr_indexer_settings
`

func (q *Queries) DeleteAllProwlarrIndexerSettings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProwlarrIndexerSettings)
	return err
}

const deleteProwlarrIndexerSettings = `-- name: DeleteProwlarrIndexerSettings :exec
DELETE FROM prowlarr_indexer_settings WHERE prowlarr_indexer_id = ?
`

func (q *Queries) DeleteProwlarrIndexerSettings(ctx context.Context, prowlarrIndexerID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProwlarrIndexerSettings, prowlarrIndexerID)
	return err
}

const getAllProwlarrIndexerSettings = `-- name: GetAllProwlarrIndexerSettings :many
SELECT prowlarr_indexer_id, priority, content_type, movie_categories, tv_categories, success_count, failure_count, last_failure_at, last_failure_reason, created_at, updated_at FROM prowlarr_indexer_settings ORDER BY prowlarr_indexer_id
`

func (q *Queries) GetAllProwlarrIndexerSettings(ctx context.Context) ([]*ProwlarrIndexerSetting, error) {
	rows, err := q.db.QueryContext(ctx, getAllProwlarrIndexerSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProwlarrIndexerSetting{}
	for rows.Next() {
		var i ProwlarrIndexerSetting
		if err := rows.Scan(
			&i.ProwlarrIndexerID,
			&i.Priority,
			&i.ContentType,
			&i.MovieCategories,
			&i.TvCategories,
			&i.SuccessCount,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProwlarrIndexerSettings = `-- name: GetProwlarrIndexerSettings :one
SELECT prowlarr_indexer_id, priority, content_type, movie_categories, tv_categories, success_count, failure_count, last_failure_at, last_failure_reason, created_at, updated_at FROM prowlarr_indexer_settings WHERE prowlarr_indexer_id = ? LIMIT 1
`

func (q *Queries) GetProwlarrIndexerSettings(ctx context.Context, prowlarrIndexerID int64) (*ProwlarrIndexerSetting, error) {
	row := q.db.QueryRowContext(ctx, getProwlarrIndexerSettings, prowlarrIndexerID)
	var i ProwlarrIndexerSetting
	err := row.Scan(
		&i.ProwlarrIndexerID,
		&i.Priority,
		&i.ContentType,
		&i.MovieCategories,
		&i.TvCategories,
		&i.SuccessCount,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProwlarrIndexerSettingsByContentType = `-- name: GetProwlarrIndexerSettingsByContentType :many
SELECT prowlarr_indexer_id, priority, content_type, movie_categories, tv_categories, success_count, failure_count, last_failure_at, last_failure_reason, created_at, updated_at FROM prowlarr_indexer_settings
WHERE content_type = ? OR content_type = 'both'
ORDER BY priority ASC
`

func (q *Queries) GetProwlarrIndexerSettingsByContentType(ctx context.Context, contentType string) ([]*ProwlarrIndexerSetting, error) {
	rows, err := q.db.QueryContext(ctx, getProwlarrIndexerSettingsByContentType, contentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ProwlarrIndexerSetting{}
	for rows.Next() {
		var i ProwlarrIndexerSetting
		if err := rows.Scan(
			&i.ProwlarrIndexerID,
			&i.Priority,
			&i.ContentType,
			&i.MovieCategories,
			&i.TvCategories,
			&i.SuccessCount,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.LastFailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProwlarrIndexerFailure = `-- name: RecordProwlarrIndexerFailure :exec
UPDATE prowlarr_indexer_settings SET
    failure_count = failure_count + 1,
    last_failure_at = CURRENT_TIMESTAMP,
    last_failure_reason = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE prowlarr_indexer_id = ?
`

type RecordProwlarrIndexerFailureParams struct {
	LastFailureReason sql.NullString `json:"last_failure_reason"`
	ProwlarrIndexerID int64          `json:"prowlarr_indexer_id"`
}

func (q *Queries) RecordProwlarrIndexerFailure(ctx context.Context, arg RecordProwlarrIndexerFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordProwlarrIndexerFailure, arg.LastFailureReason, arg.ProwlarrIndexerID)
	return err
}

const recordProwlarrIndexerSuccess = `-- name: RecordProwlarrIndexerSuccess :exec
UPDATE prowlarr_indexer_settings SET
    success_count = success_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE prowlarr_indexer_id = ?
`

func (q *Queries) RecordProwlarrIndexerSuccess(ctx context.Context, prowlarrIndexerID int64) error {
	_, err := q.db.ExecContext(ctx, recordProwlarrIndexerSuccess, prowlarrIndexerID)
	return err
}

const resetProwlarrIndexerStats = `-- name: ResetProwlarrIndexerStats :exec
UPDATE prowlarr_indexer_settings SET
    success_count = 0,
    failure_count = 0,
    last_failure_at = NULL,
    last_failure_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE prowlarr_indexer_id = ?
`

func (q *Queries) ResetProwlarrIndexerStats(ctx context.Context, prowlarrIndexerID int64) error {
	_, err := q.db.ExecContext(ctx, resetProwlarrIndexerStats, prowlarrIndexerID)
	return err
}

const upsertProwlarrIndexerSettings = `-- name: UpsertProwlarrIndexerSettings :one
INSERT INTO prowlarr_indexer_settings (
    prowlarr_indexer_id,
    priority,
    content_type,
    movie_categories,
    tv_categories
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(prowlarr_indexer_id) DO UPDATE SET
    priority = excluded.priority,
    content_type = excluded.content_type,
    movie_categories = excluded.movie_categories,
    tv_categories = excluded.tv_categories,
    updated_at = CURRENT_TIMESTAMP
RETURNING prowlarr_indexer_id, priority, content_type, movie_categories, tv_categories, success_count, failure_count, last_failure_at, last_failure_reason, created_at, updated_at
`

type UpsertProwlarrIndexerSettingsParams struct {
	ProwlarrIndexerID int64          `json:"prowlarr_indexer_id"`
	Priority          int64          `json:"priority"`
	ContentType       string         `json:"content_type"`
	MovieCategories   sql.NullString `json:"movie_categories"`
	TvCategories      sql.NullString `json:"tv_categories"`
}

func (q *Queries) UpsertProwlarrIndexerSettings(ctx context.Context, arg UpsertProwlarrIndexerSettingsParams) (*ProwlarrIndexerSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertProwlarrIndexerSettings,
		arg.ProwlarrIndexerID,
		arg.Priority,
		arg.ContentType,
		arg.MovieCategories,
		arg.TvCategories,
	)
	var i ProwlarrIndexerSetting
	err := row.Scan(
		&i.ProwlarrIndexerID,
		&i.Priority,
		&i.ContentType,
		&i.MovieCategories,
		&i.TvCategories,
		&i.SuccessCount,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.LastFailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
