// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: slot_root_folders.sql

package sqlc

import (
	"context"
)

const deleteSlotRootFolder = `-- name: DeleteSlotRootFolder :exec
DELETE FROM slot_root_folders WHERE slot_id = ? AND module_type = ?
`

type DeleteSlotRootFolderParams struct {
	SlotID     int64  `json:"slot_id"`
	ModuleType string `json:"module_type"`
}

func (q *Queries) DeleteSlotRootFolder(ctx context.Context, arg DeleteSlotRootFolderParams) error {
	_, err := q.db.ExecContext(ctx, deleteSlotRootFolder, arg.SlotID, arg.ModuleType)
	return err
}

const deleteSlotRootFolders = `-- name: DeleteSlotRootFolders :exec
DELETE FROM slot_root_folders WHERE slot_id = ?
`

func (q *Queries) DeleteSlotRootFolders(ctx context.Context, slotID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSlotRootFolders, slotID)
	return err
}

const getSlotRootFolder = `-- name: GetSlotRootFolder :one
SELECT slot_id, module_type, root_folder_id FROM slot_root_folders
WHERE slot_id = ? AND module_type = ? LIMIT 1
`

type GetSlotRootFolderParams struct {
	SlotID     int64  `json:"slot_id"`
	ModuleType string `json:"module_type"`
}

func (q *Queries) GetSlotRootFolder(ctx context.Context, arg GetSlotRootFolderParams) (*SlotRootFolder, error) {
	row := q.db.QueryRowContext(ctx, getSlotRootFolder, arg.SlotID, arg.ModuleType)
	var i SlotRootFolder
	err := row.Scan(&i.SlotID, &i.ModuleType, &i.RootFolderID)
	return &i, err
}

const listSlotRootFolders = `-- name: ListSlotRootFolders :many
SELECT slot_id, module_type, root_folder_id FROM slot_root_folders
WHERE slot_id = ?
ORDER BY module_type
`

func (q *Queries) ListSlotRootFolders(ctx context.Context, slotID int64) ([]*SlotRootFolder, error) {
	rows, err := q.db.QueryContext(ctx, listSlotRootFolders, slotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SlotRootFolder{}
	for rows.Next() {
		var i SlotRootFolder
		if err := rows.Scan(&i.SlotID, &i.ModuleType, &i.RootFolderID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSlotRootFolder = `-- name: UpsertSlotRootFolder :one
INSERT INTO slot_root_folders (slot_id, module_type, root_folder_id)
VALUES (?, ?, ?)
ON CONFLICT(slot_id, module_type) DO UPDATE SET
    root_folder_id = excluded.root_folder_id
RETURNING slot_id, module_type, root_folder_id
`

type UpsertSlotRootFolderParams struct {
	SlotID       int64  `json:"slot_id"`
	ModuleType   string `json:"module_type"`
	RootFolderID int64  `json:"root_folder_id"`
}

func (q *Queries) UpsertSlotRootFolder(ctx context.Context, arg UpsertSlotRootFolderParams) (*SlotRootFolder, error) {
	row := q.db.QueryRowContext(ctx, upsertSlotRootFolder, arg.SlotID, arg.ModuleType, arg.RootFolderID)
	var i SlotRootFolder
	err := row.Scan(&i.SlotID, &i.ModuleType, &i.RootFolderID)
	return &i, err
}
