// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_notifications.sql

package sqlc

import (
	"context"
)

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*) FROM user_notifications WHERE user_id = ?
`

func (q *Queries) CountUserNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserNotification = `-- name: CreateUserNotification :one
INSERT INTO user_notifications (
    user_id, type, name, settings, on_available, on_approved, on_denied, enabled
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied
`

type CreateUserNotificationParams struct {
	UserID      int64  `json:"user_id"`
	Type        string `json:"type"`
	Name        string `json:"name"`
	Settings    string `json:"settings"`
	OnAvailable int64  `json:"on_available"`
	OnApproved  int64  `json:"on_approved"`
	OnDenied    int64  `json:"on_denied"`
	Enabled     int64  `json:"enabled"`
}

func (q *Queries) CreateUserNotification(ctx context.Context, arg CreateUserNotificationParams) (*UserNotification, error) {
	row := q.db.QueryRowContext(ctx, createUserNotification,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Settings,
		arg.OnAvailable,
		arg.OnApproved,
		arg.OnDenied,
		arg.Enabled,
	)
	var i UserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Settings,
		&i.OnAvailable,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnApproved,
		&i.OnDenied,
	)
	return &i, err
}

const deleteUserNotification = `-- name: DeleteUserNotification :exec
DELETE FROM user_notifications WHERE id = ?
`

func (q *Queries) DeleteUserNotification(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserNotification, id)
	return err
}

const deleteUserNotificationsByUser = `-- name: DeleteUserNotificationsByUser :exec
DELETE FROM user_notifications WHERE user_id = ?
`

func (q *Queries) DeleteUserNotificationsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserNotificationsByUser, userID)
	return err
}

const getUserNotification = `-- name: GetUserNotification :one
SELECT id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied FROM user_notifications WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserNotification(ctx context.Context, id int64) (*UserNotification, error) {
	row := q.db.QueryRowContext(ctx, getUserNotification, id)
	var i UserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Settings,
		&i.OnAvailable,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnApproved,
		&i.OnDenied,
	)
	return &i, err
}

const listEnabledUserNotifications = `-- name: ListEnabledUserNotifications :many
SELECT id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied FROM user_notifications
WHERE user_id = ? AND enabled = 1
ORDER BY name
`

func (q *Queries) ListEnabledUserNotifications(ctx context.Context, userID int64) ([]*UserNotification, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Settings,
			&i.OnAvailable,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnApproved,
			&i.OnDenied,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied FROM user_notifications
WHERE user_id = ?
ORDER BY name
`

func (q *Queries) ListUserNotifications(ctx context.Context, userID int64) ([]*UserNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Settings,
			&i.OnAvailable,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnApproved,
			&i.OnDenied,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotificationsForApproved = `-- name: ListUserNotificationsForApproved :many
SELECT id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied FROM user_notifications
WHERE user_id = ? AND enabled = 1 AND on_approved = 1
ORDER BY name
`

func (q *Queries) ListUserNotificationsForApproved(ctx context.Context, userID int64) ([]*UserNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotificationsForApproved, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Settings,
			&i.OnAvailable,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnApproved,
			&i.OnDenied,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotificationsForAvailable = `-- name: ListUserNotificationsForAvailable :many
SELECT id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied FROM user_notifications
WHERE user_id = ? AND enabled = 1 AND on_available = 1
ORDER BY name
`

func (q *Queries) ListUserNotificationsForAvailable(ctx context.Context, userID int64) ([]*UserNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotificationsForAvailable, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Settings,
			&i.OnAvailable,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnApproved,
			&i.OnDenied,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotificationsForDenied = `-- name: ListUserNotificationsForDenied :many
SELECT id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied FROM user_notifications
WHERE user_id = ? AND enabled = 1 AND on_denied = 1
ORDER BY name
`

func (q *Queries) ListUserNotificationsForDenied(ctx context.Context, userID int64) ([]*UserNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotificationsForDenied, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.Settings,
			&i.OnAvailable,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnApproved,
			&i.OnDenied,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserNotification = `-- name: UpdateUserNotification :one
UPDATE user_notifications SET
    name = ?,
    type = ?,
    settings = ?,
    on_available = ?,
    on_approved = ?,
    on_denied = ?,
    enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, type, name, settings, on_available, enabled, created_at, updated_at, on_approved, on_denied
`

type UpdateUserNotificationParams struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Settings    string `json:"settings"`
	OnAvailable int64  `json:"on_available"`
	OnApproved  int64  `json:"on_approved"`
	OnDenied    int64  `json:"on_denied"`
	Enabled     int64  `json:"enabled"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUserNotification(ctx context.Context, arg UpdateUserNotificationParams) (*UserNotification, error) {
	row := q.db.QueryRowContext(ctx, updateUserNotification,
		arg.Name,
		arg.Type,
		arg.Settings,
		arg.OnAvailable,
		arg.OnApproved,
		arg.OnDenied,
		arg.Enabled,
		arg.ID,
	)
	var i UserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.Settings,
		&i.OnAvailable,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OnApproved,
		&i.OnDenied,
	)
	return &i, err
}
